"""
Optimized Auto Skill Generator.

Improvements over Hermes' built-in skill generation:
  1. Pattern-based detection of repeatable workflows
  2. Multi-session correlation for skill relevance
  3. Template-based skill generation with versioning
  4. Skill effectiveness tracking with auto-retirement
  5. Integration with workflow memory decay system
  6. Conflict detection to prevent duplicate skills
  7. Config-driven skill customization

Skills are auto-generated by:
  1. Analyzing conversation patterns across sessions
  2. Detecting repeated tool-use sequences
  3. Identifying problem→solution patterns
  4. Generating SKILL.md with proper YAML frontmatter
  5. Assigning initial effectiveness score
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from hermes_constants import get_skills_dir

from .gateway import UnifiedMemoryGateway
from .workflow import WorkflowEntry

logger = logging.getLogger(__name__)

SKILL_TEMPLATE = """---
name: {name}
description: {description}
version: {version}
metadata:
  hermes:
    auto_generated: true
    generated_at: {generated_at}
    source_workflows: {source_workflows}
    usage_count: 0
    effectiveness: {initial_effectiveness}
    tags: {tags}
---

# {title}

{description}

## When to Use

{when_to_use}

## Steps

{steps}

## Expected Outcome

{expected_outcome}

## Notes

- Auto-generated from {usage_count} session(s) of interaction patterns
- Effectiveness score: {initial_effectiveness:.2f} (adjusts with usage)
- Last updated: {generated_at}
"""


class SkillAutoGenerator:
    """Generates and manages skills from detected workflow patterns."""

    def __init__(self, gateway: UnifiedMemoryGateway,
                 skills_dir: Optional[Path] = None,
                 min_pattern_occurrences: int = 3,
                 min_session_correlation: int = 2,
                 generation_cooldown_hours: float = 1.0):
        self._gateway = gateway
        self._skills_dir = skills_dir or get_skills_dir()
        self._min_pattern_occurrences = min_pattern_occurrences
        self._min_session_correlation = min_session_correlation
        self._generation_cooldown_hours = generation_cooldown_hours
        self._last_generation: Dict[str, float] = {}
        self._skill_cache: Dict[str, Dict] = {}

    def scan_and_generate(self) -> List[Dict[str, Any]]:
        """Main entry point: scan workflows and generate skills.

        Returns list of generated skill descriptors.
        """
        generated = []

        # Get all workflows with sufficient usage
        workflows = self._gateway._wfm._store.get_all_workflows()
        candidates = [w for w in workflows
                      if w.usage_count >= self._min_pattern_occurrences
                      and w.current_weight > 0.2]

        for wf in candidates:
            # Check cooldown
            if not self._can_generate(wf.name):
                continue

            # Check if skill already exists
            if self._skill_exists(wf.name):
                # Update existing skill effectiveness
                self._update_skill_effectiveness(wf)
                continue

            # Check for similar existing skills (conflict detection)
            if self._has_conflict(wf):
                continue

            # Generate the skill
            skill_info = self._generate_skill_from_workflow(wf)
            if skill_info:
                generated.append(skill_info)
                self._last_generation[wf.name] = datetime.now(timezone.utc).timestamp()

        return generated

    def _can_generate(self, workflow_name: str) -> bool:
        """Check if generation cooldown has elapsed."""
        last = self._last_generation.get(workflow_name, 0)
        if last == 0:
            return True
        cooldown = self._generation_cooldown_hours * 3600
        return (datetime.now(timezone.utc).timestamp() - last) >= cooldown

    def _skill_exists(self, workflow_name: str) -> bool:
        """Check if a skill for this workflow already exists."""
        skill_name = f"auto-{self._sanitize_name(workflow_name)}"
        skill_dir = self._skills_dir / skill_name
        return (skill_dir / "SKILL.md").exists()

    def _has_conflict(self, workflow: WorkflowEntry) -> bool:
        """Check for conflicts with existing skills."""
        target_name = self._sanitize_name(workflow.name)

        if not self._skills_dir.exists():
            return False

        for skill_md in self._skills_dir.rglob("SKILL.md"):
            skill_dir_name = skill_md.parent.name.lower()
            if skill_dir_name == f"auto-{target_name}":
                return True

            # Check name similarity
            similarity = self._name_similarity(target_name, skill_dir_name)
            if similarity > 0.7:
                return True

            # Check trigger pattern overlap
            try:
                content = skill_md.read_text(encoding="utf-8")
                for pattern in workflow.trigger_patterns:
                    if pattern.lower() in content.lower():
                        return True
            except Exception:
                pass

        return False

    def _name_similarity(self, a: str, b: str) -> float:
        """Simple Jaccard similarity of character bigrams."""
        def bigrams(s):
            return set(s[i:i+2] for i in range(len(s)-1))

        ba = bigrams(a.lower())
        bb = bigrams(b.lower())
        if not ba or not bb:
            return 0.0
        return len(ba & bb) / len(ba | bb)

    def _generate_skill_from_workflow(self, workflow: WorkflowEntry) -> Optional[Dict[str, Any]]:
        """Generate a SKILL.md from a workflow entry."""
        try:
            name = self._sanitize_name(workflow.name)
            skill_name = f"auto-{name}"
            skill_dir = self._skills_dir / skill_name
            skill_dir.mkdir(parents=True, exist_ok=True)

            # Prepare template variables
            title = workflow.name.replace("-", " ").replace("_", " ").title()
            when_to_use = "\n".join(
                f"- When user mentions: {p}" for p in workflow.trigger_patterns[:5]
            ) if workflow.trigger_patterns else "- When the conversation patterns match"

            steps_md = "\n".join(
                f"{i+1}. {step}" for i, step in enumerate(workflow.steps[:10])
            ) if workflow.steps else "No steps defined yet."

            # Initial effectiveness based on workflow stats
            success_rate = workflow.success_count / max(1, workflow.usage_count)
            initial_effectiveness = 0.5 + 0.4 * success_rate + 0.1 * min(workflow.usage_count / 10.0, 1.0)

            content = SKILL_TEMPLATE.format(
                name=skill_name,
                description=workflow.description[:500],
                version=f"{workflow.version}.0",
                generated_at=datetime.now(timezone.utc).isoformat(),
                source_workflows=json.dumps([workflow.name]),
                initial_effectiveness=min(1.0, initial_effectiveness),
                tags=json.dumps(workflow.trigger_patterns[:5]),
                title=title,
                when_to_use=when_to_use,
                steps=steps_md,
                expected_outcome=workflow.expected_outcome or "Task completed successfully",
                usage_count=workflow.usage_count,
            )

            skill_file = skill_dir / "SKILL.md"
            skill_file.write_text(content, encoding="utf-8")

            # Update workflow with skill path via public method
            gw = self._gateway
            wf_entry = gw._wfm._store.get_workflow(workflow.name)
            if wf_entry:
                wf_entry.skill_md_path = str(skill_file)
                gw._wfm._store.upsert_workflow(wf_entry)

            skill_info = {
                "name": skill_name,
                "path": str(skill_file),
                "workflow": workflow.name,
                "initial_effectiveness": initial_effectiveness,
                "usage_count": workflow.usage_count,
            }

            logger.info("Auto-generated skill '%s' from workflow '%s' (effectiveness=%.2f)",
                         skill_name, workflow.name, initial_effectiveness)
            return skill_info

        except Exception as e:
            logger.error("Failed to generate skill from workflow '%s': %s", workflow.name, e)
            return None

    def _update_skill_effectiveness(self, workflow: WorkflowEntry):
        """Update an existing skill's effectiveness based on workflow stats."""
        skill_name = f"auto-{self._sanitize_name(workflow.name)}"
        skill_file = self._skills_dir / skill_name / "SKILL.md"

        if not skill_file.exists():
            return

        try:
            content = skill_file.read_text(encoding="utf-8")
            success_rate = workflow.success_count / max(1, workflow.usage_count)
            new_effectiveness = 0.5 + 0.4 * success_rate + 0.1 * min(workflow.usage_count / 10.0, 1.0)

            # Update effectiveness in frontmatter
            content = re.sub(
                r'effectiveness:\s*[\d.]+',
                f'effectiveness: {new_effectiveness:.2f}',
                content,
            )
            content = re.sub(
                r'usage_count:\s*\d+',
                f'usage_count: {workflow.usage_count}',
                content,
            )

            skill_file.write_text(content, encoding="utf-8")
            self._skill_cache[workflow.name] = {
                "effectiveness": new_effectiveness,
                "updated_at": datetime.now(timezone.utc).timestamp(),
            }

        except Exception as e:
            logger.debug("Failed to update skill effectiveness: %s", e)

    def _sanitize_name(self, name: str) -> str:
        """Sanitize a workflow name for use as a skill name."""
        name = name.lower()
        name = re.sub(r'[^a-z0-9]+', '-', name)
        name = name.strip('-')
        return name[:50] if name else "generated"

    def detect_patterns_from_history(self, sessions: List[Dict]) -> List[Dict]:
        """Advanced pattern detection across multiple sessions.

        Args:
            sessions: List of session dicts with 'messages' key

        Returns:
            List of detected pattern dicts
        """
        if len(sessions) < self._min_session_correlation:
            return []

        # Extract tool-call sequences from sessions
        tool_sequences: Dict[str, List[List[str]]] = {}
        for session in sessions:
            session_id = session.get("session_id", "")
            messages = session.get("messages", [])
            tools = self._extract_tool_sequence(messages)
            if tools:
                tool_sequences.setdefault(session_id, []).append(tools)

        # Find repeated sequences across sessions
        patterns = self._find_repeated_sequences(tool_sequences)
        return patterns

    def _extract_tool_sequence(self, messages: List[Dict]) -> List[str]:
        """Extract tool call sequence from messages."""
        tools = []
        for msg in messages:
            tool_calls = msg.get("tool_calls", [])
            for tc in tool_calls:
                func = tc.get("function", {})
                name = func.get("name", "")
                if name:
                    tools.append(name)
        return tools

    def _find_repeated_sequences(self, tool_sequences: Dict[str, List[List[str]]]) -> List[Dict]:
        """Find tool sequences that repeat across sessions."""
        sequence_map: Dict[str, Dict] = {}

        for session_id, sequences in tool_sequences.items():
            for seq in sequences:
                key = hashlib.md5("|".join(seq).encode()).hexdigest()
                if key not in sequence_map:
                    sequence_map[key] = {
                        "tools": list(dict.fromkeys(seq)),
                        "sessions": set(),
                        "count": 0,
                    }
                sequence_map[key]["sessions"].add(session_id)
                sequence_map[key]["count"] += 1

        return [
            v for v in sequence_map.values()
            if len(v["sessions"]) >= self._min_session_correlation
            and v["count"] >= self._min_pattern_occurrences
        ]

    def get_skill_stats(self) -> List[Dict]:
        """Get statistics for all auto-generated skills."""
        stats = []
        if not self._skills_dir.exists():
            return stats

        for skill_md in self._skills_dir.rglob("SKILL.md"):
            try:
                content = skill_md.read_text(encoding="utf-8")
                if "auto_generated: true" not in content:
                    continue

                name_match = re.search(r'^name:\s*(.+)$', content, re.MULTILINE)
                eff_match = re.search(r'effectiveness:\s*([\d.]+)', content)
                usage_match = re.search(r'usage_count:\s*(\d+)', content)

                stats.append({
                    "name": name_match.group(1).strip() if name_match else skill_md.parent.name,
                    "path": str(skill_md),
                    "effectiveness": float(eff_match.group(1)) if eff_match else 0.0,
                    "usage_count": int(usage_match.group(1)) if usage_match else 0,
                })
            except Exception:
                pass

        return sorted(stats, key=lambda s: -s["effectiveness"])

    def retire_low_effectiveness_skills(self, threshold: float = 0.15) -> List[str]:
        """Retire auto-generated skills that have low effectiveness."""
        retired = []
        stats = self.get_skill_stats()

        for skill in stats:
            if skill["effectiveness"] < threshold:
                skill_file = Path(skill["path"])
                try:
                    # Don't delete, just mark as retired
                    content = skill_file.read_text(encoding="utf-8")
                    content = content.replace(
                        "auto_generated: true",
                        "auto_generated: true\n    retired: true",
                    )
                    skill_file.write_text(content, encoding="utf-8")
                    retired.append(skill["name"])
                    logger.info("Retired low-effectiveness skill: %s (eff=%.2f)",
                                skill["name"], skill["effectiveness"])
                except Exception as e:
                    logger.warning("Failed to retire skill %s: %s", skill["name"], e)

        return retired
