#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""QQBot Installer -- create HERMES_HOME and deploy config templates"""
import os, re, shutil
from pathlib import Path

BOT_DIR = Path(__file__).resolve().parent.parent  # bot-template root
HERMES_HOME = Path.home() / ".hermes"

def detect_bot_name() -> str:
    """Extract bot name from SOUL.md first line: '# SOUL.md — 長崎素世' → 素世"""
    for path in (HERMES_HOME / "SOUL.md", BOT_DIR / "templates" / "SOUL.md"):
        if path.exists():
            try:
                first = path.read_text(encoding="utf-8", errors="replace").splitlines()[0]
                m = re.search(r'[—\-]\s*(.+)$', first)
                if m:
                    return m.group(1).strip()
            except Exception:
                pass
    return "Soyo"

def setup():
    HERMES_HOME.mkdir(parents=True, exist_ok=True)
    print(f"HERMES_HOME: {HERMES_HOME}")

    bot_name = detect_bot_name()
    print(f"  Detected bot name: {bot_name}")

    # Write minimal .env (API keys filled later by 配置API.bat)
    env_file = HERMES_HOME / ".env"
    if not env_file.exists():
        env_lines = [
            "# Auto-generated by install.py",
            "GATEWAY_ALLOW_ALL_USERS=true",
            "ONEBOT_WS_URL=ws://127.0.0.1:3001/",
            "ONEBOT_HTTP_URL=http://127.0.0.1:3000",
            f"ONEBOT_BOT_NAME={bot_name}",
            "ONEBOT_SELF_ID=",
            "ONEBOT_ADMIN_ID=",
            "DEEPSEEK_API_KEY=",
            "DEEPSEEK_BASE_URL=",
            "DEEPSEEK_MODEL=",
        ]
        env_file.write_text("\n".join(env_lines) + "\n", encoding="utf-8")
        print("  .env created (with ONEBOT_BOT_NAME)")
    else:
        # .env 已存在但缺 ONEBOT_BOT_NAME → 追加
        # 容错读取：用户手动编辑可能引入非 UTF-8 字节（GBK/截断序列）
        try:
            content = env_file.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            content = env_file.read_text(encoding="utf-8", errors="replace")
        if "ONEBOT_BOT_NAME" not in content:
            with env_file.open("a", encoding="utf-8") as f:
                f.write(f"\nONEBOT_BOT_NAME={bot_name}\n")
            print("  ONEBOT_BOT_NAME appended to .env")
        elif bot_name != "Soyo":
            # 更新角色名
            content = re.sub(r'^ONEBOT_BOT_NAME=.*$', f'ONEBOT_BOT_NAME={bot_name}',
                             content, flags=re.MULTILINE)
            env_file.write_text(content, encoding="utf-8")
            print(f"  ONEBOT_BOT_NAME updated to {bot_name}")

    # Copy config template only
    tpl_dir = BOT_DIR / "templates"
    for fname in ("config-template.yaml",):
        src = tpl_dir / fname
        dst_name = fname.replace("-template", "")
        dst = HERMES_HOME / dst_name
        if src.exists() and not dst.exists():
            shutil.copy(src, dst)
            print(f"  Created {dst_name} -> {dst}")

    print()
    print("Done! Base config files created.")

    # Create knowledge directory (project-local modules/knowledge,
    # matches gateway.py OBSIDIAN_VAULT_PATH fallback)
    kb = BOT_DIR / "modules" / "knowledge"
    kb.mkdir(parents=True, exist_ok=True)
    (kb / ".gitkeep").touch(exist_ok=True)
    print(f"  Knowledge dir: {kb}")

    print()
    print("Next: run the API config tool to set up your LLM provider.")

if __name__ == "__main__":
    setup()
